version: "3.3"
services:
  rabbitmq-stats:
    image: index.docker.io/bitnami/rabbitmq:3.8
    hostname: rabbitmq-stats
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq-stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=1
    restart: on-failure:5
    volumes:
      - ./data/rabbitmq/custom.conf:/bitnami/rabbitmq/conf/custom.conf:z
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 2G
  mongodb-primary:
    image: index.docker.io/bitnami/mongodb:4.4
    hostname: mongodb-primary
    volumes:
      - ./data/mongo-data:/bitnami/mongodb:z
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=cte
    restart: on-failure:5
    ports:
      - "27017:27017"
    logging:
      options:
        max-size: "10m"
        max-file: "5"
  core:
    image: index.docker.io/${CORE_TAG}
    volumes:
      - ./data/custom_plugins:/opt/netskope/plugins/custom_plugins:z
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: core
    environment:
      - MONGO_CONNECTION_STRING=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb-primary:27017/cte
      - RABBITMQ_CONNECTION_STRING=amqp://user:bitnami@rabbitmq-stats
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - ENABLE_CELERY_BEAT=true
      #- DOCKER_USERNAME=${DOCKER_USERNAME}
      #- DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
      - ANALYTICS_BASE_URL=https://reporting.netskope.tech
      - ANALYTICS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbnN0YWxsYXRpb25faWQiOiJjMDAyIn0.w8SVrTcDjk8PkR4IcbWGwOyf6-OWfCUyOoCTgZvqHqc
      - MAX_MAINTENANCE_WINDOW_MINUTES=${MAX_MAINTENANCE_WINDOW_MINUTES}
      - PULL_THREADS=${PULL_THREADS}
      - MAX_WAIT_ON_LOCK_IN_MINUTES=${MAX_WAIT_ON_LOCK_IN_MINUTES}
    restart: on-failure:5
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - mongodb-primary
      - rabbitmq-stats
    labels:
      - com.centurylinklabs.watchtower.enable=true
  ui:
    image: index.docker.io/${UI_TAG}
    hostname: ui
    restart: on-failure:5
    environment:
      - CE_API_URL=http://core
    volumes:
      - ./data/ssl_certs:/tmp/ssl_certs:z
    ports:
      - ${UI_PORT}:3000
    links:
      - core
    labels:
      - com.centurylinklabs.watchtower.enable=true
    logging:
      options:
        max-size: "10m"
        max-file: "5"
