version: "3.3"
services:
  rabbitmq-stats:
    image: index.docker.io/rabbitmq:3.9-management
    user: "1001:1001"
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq-stats
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=${MAINTENANCE_PASSWORD}
      - RABBITMQ_DISK_FREE_LIMIT_ABSOLUTE=1
    restart: always
    volumes:
      - ./data/rabbitmq/custom.conf:/etc/rabbitmq/conf.d/custom.conf:z
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 2G
    entrypoint: ["/bin/bash","-c","echo ${MAINTENANCE_PASSWORD} > /var/lib/rabbitmq/.erlang.cookie && chmod 600 /var/lib/rabbitmq/.erlang.cookie && docker-entrypoint.sh rabbitmq-server"]
  mongodb-primary:
    image: index.docker.io/mongo:5.0
    user: mongodb
    volumes:
      - ./data/mongo-data/data/db:/data/db:z
      - ./data/database-init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:z
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MAINTENANCE_PASSWORD}
      - MONGO_INITDB_DATABASE=cte
      - MONGODB_USERNAME=cteadmin
      - MONGODB_PASSWORD=${MAINTENANCE_PASSWORD}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"
  core:
    image: index.docker.io/${CORE_TAG}
    volumes:
      - ./data/custom_plugins:/opt/netskope/plugins/custom_plugins:z
      - ./data/ca_certs:/usr/local/share/ca-certificates:z
    environment:
      - MONGO_CONNECTION_STRING=mongodb://cteadmin:${MAINTENANCE_PASSWORD_ESCAPED}@mongodb-primary:27017/cte
      - RABBITMQ_CONNECTION_STRING=amqp://user:${MAINTENANCE_PASSWORD_ESCAPED}@rabbitmq-stats
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - ENABLE_CELERY_BEAT=true
      - DOCKER_USERNAME=${DOCKER_USERNAME:-}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD:-}
      - CORE_TAG=${CORE_TAG}
      - UI_TAG=${UI_TAG}
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
      - ANALYTICS_BASE_URL=https://reporting.netskope.tech
      - ANALYTICS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbnN0YWxsYXRpb25faWQiOiJjMDAyIn0.w8SVrTcDjk8PkR4IcbWGwOyf6-OWfCUyOoCTgZvqHqc
      - MAX_MAINTENANCE_WINDOW_MINUTES=${MAX_MAINTENANCE_WINDOW_MINUTES}
      - PULL_THREADS=${PULL_THREADS}
      - MAX_WAIT_ON_LOCK_IN_MINUTES=${MAX_WAIT_ON_LOCK_IN_MINUTES}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - BETA_OPT_IN=${BETA_OPT_IN}
      - REQUESTS_TIMEOUT=${REQUESTS_TIMEOUT}
      - POPEN_TIMEOUT=${POPEN_TIMEOUT}
      # - UI_SERVICE_NAME=
      # - THRESHOLD_FOR_IDLE_CHECK_IN_MINUTES=
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - mongodb-primary
      - rabbitmq-stats
    labels:
      - com.centurylinklabs.watchtower.enable=true
  ui:
    image: index.docker.io/${UI_TAG}
    restart: always
    environment:
      - CE_API_URL=http://core
      - CE_API_PORT=8000
      - TLS_VERSION=${ENABLE_TLS_V_1_2:-TLSv1.3}
    volumes:
      - ./data/ssl_certs:/tmp/ssl_certs:z
    ports:
      - ${UI_PORT}:3000
    links:
      - core
    labels:
      - com.centurylinklabs.watchtower.enable=true
    logging:
      options:
        max-size: "10m"
        max-file: "5"
