#!/bin/sh

set -a
. ./.env
set -e

RETRIES=5
SLEEP=3
DB_VERSION_ENV_FILE_LOCATION="./.env.ceversion"
VENV_DIR=".cevenv"
ACTIVATE_SCRIPT_PATH="${VENV_DIR}/bin/activate"

if [ -n "${HA_IP_LIST}" ]; then
    # Check if virtual environment already exists
    if [ -d "${VENV_DIR}" ] && [ -f "${ACTIVATE_SCRIPT_PATH}" ]; then
        echo "Virtual environment '$VENV_DIR' already exists."
        echo "Using existing virtual environment."
        echo "${ACTIVATE_SCRIPT_PATH}"
        . "${ACTIVATE_SCRIPT_PATH}"
    else
        echo "Virtual environment '${VENV_DIR}' or '${ACTIVATE_SCRIPT_PATH}' does not exist, Please run setup first."
        exit 1
    fi
fi

if [ -n "$HA_NFS_DATA_DIRECTORY" ]; then
    mounted=false
    missing_volume=false
    service_exists=false

   if systemctl list-unit-files | grep -q "^glusterd\.service"; then
    echo "glusterd service found."
    service_exists=true
        if ! systemctl is-active --quiet glusterd; then
            echo "glusterd service is not running. Attempting to start it..."
            sudo systemctl start glusterd
            for i in $(seq 1 $RETRIES); do
                if systemctl is-active --quiet glusterd; then
                    echo "glusterd service is now running."
                    break
                else
                    echo "Waiting for glusterd service... ($i/$RETRIES)"
                    sleep "$SLEEP"
                fi

                if [ "$i" -eq "$RETRIES" ]; then
                    echo "Failed to start glusterd service after $RETRIES attempts."
                fi
            done
        fi
    fi

    if $service_exists && ! gluster volume info CloudExchange | grep -q 'Volume Name: CloudExchange'; then
        echo "CloudExchange Volume not found"
        missing_volume=true
    fi

    if [ "$missing_volume" = false ]; then
        if mountpoint -q "$HA_NFS_DATA_DIRECTORY"; then
            echo "Already mounted: $HA_NFS_DATA_DIRECTORY"
            mounted=true
        else
            for i in $(seq 1 $RETRIES); do
                echo "Attempting to mount CloudExchange (try $i)..."
                if mount -t glusterfs "$HA_CURRENT_NODE:/CloudExchange" "$HA_NFS_DATA_DIRECTORY"; then
                    echo "Mount successful"
                    mounted=true
                    break
                else
                    echo "Mount attempt $i failed"
                    sleep "$SLEEP"
                fi
            done
        fi
    fi

    if [ "$missing_volume" = true ] || [ "$mounted" = false ]; then
        ENV_FILE="./.env"
    else
        if [ -f "$HA_NFS_DATA_DIRECTORY/config/.env" ]; then
            ENV_FILE="$HA_NFS_DATA_DIRECTORY/config/.env"
            DB_VERSION_ENV_FILE_LOCATION="$HA_NFS_DATA_DIRECTORY/config/.env.ceversion"
        else
            echo "Expected shared .env not found, falling back"
            ENV_FILE="./.env"
        fi
    fi
else
    ENV_FILE="./.env"
fi

. ${ENV_FILE}
set +a

python3 data/management_server/management_server.py
