#!/bin/sh

set -a
. ./.env
. ${ENV_FILE}
set +a

VENV_DIR=".cevenv"
ACTIVATE_SCRIPT_PATH="${VENV_DIR}/bin/activate"

if [ -f /etc/redhat-release ] && [ `grep -c "Red Hat" /etc/redhat-release` -eq 1 ]; then  
    if [ `grep -c "7.9" /etc/redhat-release` -ge 1 ]; then
        docker compose version &> /dev/null
        if [ $? -eq 127 ]; then
            echo "Could not find docker compose"
            exit 1;
        else
            if [ -z "${HA_IP_LIST}" ]; then
                alias compose_command="docker compose -f docker-compose.yml"
            else
                alias compose_command="docker compose -f docker-compose-ha.yml"
            fi
        fi
    else
        podman-compose version &> /dev/null
        if [ $? -eq 127 ]; then
            echo "Could not find podman-compose"
            exit 1;
        else
            if [ -z "${HA_IP_LIST}" ]; then
                alias compose_command="podman-compose -f podman-compose.yml"
            else
                alias compose_command="podman-compose -f podman-compose-ha.yml"
            fi
        fi
    fi
else
    docker compose version &> /dev/null
    if [ $? -eq 127 ]; then
        podman-compose version &> /dev/null
        if [ $? -eq 127 ]; then
            echo "Could not find docker compose or podman-compose"
            exit 1;
        else
            if [ -z "${HA_IP_LIST}" ]; then
                alias compose_command="podman-compose -f podman-compose.yml"
            else
                alias compose_command="podman-compose -f podman-compose-ha.yml"
            fi
        fi
    else
        if [ -z "${HA_IP_LIST}" ]; then
            alias compose_command="docker compose -f docker-compose.yml"
        else
            alias compose_command="docker compose -f docker-compose-ha.yml"
        fi
    fi
fi

if [ -n "${HA_IP_LIST}" ]; then
    # Check if virtual environment already exists
    if [ -d "${VENV_DIR}" ] && [ -f "${ACTIVATE_SCRIPT_PATH}" ]; then
        echo "Virtual environment '$VENV_DIR' already exists."
        echo "Using existing virtual environment."
        echo "${ACTIVATE_SCRIPT_PATH}"
        . "${ACTIVATE_SCRIPT_PATH}"
    else
        echo "Virtual environment '${VENV_DIR}' or '${ACTIVATE_SCRIPT_PATH}' does not exist, Please run setup first."
        exit 1
    fi
fi


if [ -n "${HA_IP_LIST}" ]; then
    ./replica_set --remove

    RETURN=$?
    if [ $RETURN -eq 0 ]; then
        compose_command exec -- rabbitmq-stats rabbitmq-queues delete_member cloudexchange_9 rabbit@$HA_CURRENT_NODE
        compose_command exec -- rabbitmq-stats rabbitmq-queues delete_member cloudexchange_6 rabbit@$HA_CURRENT_NODE
        compose_command exec -- rabbitmq-stats rabbitmq-queues delete_member cloudexchange_3 rabbit@$HA_CURRENT_NODE

        compose_command exec -- rabbitmq-stats rabbitmqctl stop_app
        compose_command exec -- rabbitmq-stats rabbitmqctl reset
    elif [ $RETURN -eq 1 ]; then
        exit 0
    fi
fi

compose_command down -v

